const q = (question, answer, explanation, source, media = {}) => ({
  key: answer,
  question,
  definition: `${answer}. ${explanation}`,
  explanation,
  source,
  ...media,
})

const topic = (title, items) => ({ title, items })

// Original practice questions based on the Highway Code and official GOV.UK guidance.
// They are not copied from, or represented as, the licensed DVSA revision question bank.
export const drivingTheoryDeck = {
  id: 'uk-car-theory-gb-2026',
  title: 'UK Car Theory — Complete Topic Practice',
  subject: 'Driving theory · Great Britain',
  category: 'Driving',
  status: 'Current',
  courseSubject: 'Driving theory',
  cover: './assets/covers/driving.webp',
  coverAlt: 'A learner driver approaching a British roundabout',
  features: ['theory', 'hazard', 'generic'],
  description: '120 original questions, including official sign images, across all 14 car-theory topics; reviewed against the Highway Code in July 2026.',
  attribution: 'Contains public sector information licensed under the Open Government Licence v3.0. Not affiliated with or endorsed by DVSA.',
  topics: [
    topic('Alertness', [
      q('What should you do before changing direction or speed?', 'Check your mirrors', 'Know what is behind and beside you before signalling or acting.', 'Highway Code rule 103'),
      q('What extra check is needed before moving off?', 'Check the blind spot', 'Mirrors cannot show every area, so look around before moving.', 'Highway Code rule 159'),
      q('What is the safest response when you begin to feel sleepy?', 'Stop somewhere safe and rest', 'Fresh air or loud music cannot reliably overcome tiredness.', 'Highway Code rule 91'),
      q('What should you do if oncoming headlights dazzle you?', 'Slow down and stop if necessary', 'Avoid staring at the lights and make sure you can stop within the distance you can see.', 'Highway Code rule 115'),
      q('When should you use mirrors while driving?', 'Frequently and before every manoeuvre', 'Regular mirror checks keep your picture of surrounding traffic current.', 'Highway Code rules 103 and 161'),
      q('What should you do when a distraction inside the car needs attention?', 'Stop in a safe place first', 'Taking your eyes or mind off the road reduces hazard detection.', 'Highway Code rules 148 to 150'),
      q('What does fatigue do to driving ability?', 'Slows reactions and reduces concentration', 'Tired drivers process hazards later and make poorer decisions.', 'Highway Code rule 91'),
      q('When approaching a hidden junction, what should you expect?', 'A road user may emerge unexpectedly', 'Reduce speed and scan early where your view is restricted.', 'Highway Code rules 146 and 170'),
    ]),
    topic('Attitude', [
      q('What does flashing your headlights mean?', 'I am here', 'It does not give priority or invite another road user to proceed.', 'Highway Code rule 110'),
      q('What should you do if another driver is following too closely?', 'Increase the gap ahead', 'This gives you more room to slow gradually and reduces the chance of a collision.', 'Highway Code rule 126'),
      q('When may you use the horn while stationary?', 'Only when another road user poses a danger', 'The horn is a warning device, not a way to show annoyance.', 'Highway Code rule 112'),
      q('When must you avoid sounding the horn in a built-up area?', 'Between 11:30 pm and 7:00 am', 'The restriction applies unless another road user poses a danger.', 'Highway Code rule 112'),
      q('How should you respond to an inexperienced driver who stalls?', 'Be patient and allow time', 'Pressure or aggression can make an unsafe situation worse.', 'Highway Code rules 144 and 147'),
      q('What is the main purpose of giving a signal?', 'To help other road users', 'Signals should be clear, correctly timed and cancelled after use.', 'Highway Code rule 103'),
      q('What should you do when an emergency vehicle approaches?', 'Let it pass when safe', 'Do not panic, break traffic laws or put others in danger.', 'Highway Code rule 219'),
      q('Who carries the greatest responsibility to reduce danger?', 'Road users who can cause the greatest harm', 'The hierarchy does not remove anyone else’s responsibility to behave safely.', 'Highway Code rule H1'),
    ]),
    topic('Safety and your vehicle', [
      q('What is the minimum legal tyre tread depth for most cars?', '1.6 mm', 'It must cover the central three-quarters of the tyre breadth around the entire circumference.', 'Highway Code annex 6'),
      q('When should tyre pressures normally be checked?', 'When the tyres are cold', 'Use the vehicle manufacturer’s recommended pressures and adjust for heavy loads.', 'Highway Code annex 6'),
      q('What should you do if a brake warning light stays on?', 'Have the brakes checked immediately', 'A persistent warning can indicate a dangerous braking-system fault.', 'Highway Code rule 89 and annex 6'),
      q('How should a head restraint be positioned?', 'Its rigid part level with the eyes or top of the ears', 'It should also be as close to the back of the head as is comfortable.', 'Highway Code rule 97'),
      q('What should be kept clean and unobstructed before driving?', 'Lights, windows, mirrors and number plates', 'Being able to see and be seen is essential and number plates must remain legible.', 'Highway Code rule 97 and annex 6'),
      q('What is the main benefit of anti-lock brakes?', 'They help retain steering control during hard braking', 'ABS does not remove the need for safe speed and distance.', 'Highway Code rule 120'),
      q('Who is responsible for making sure a child under 14 is restrained?', 'The driver', 'The correct child restraint or seat belt must be used, subject to limited exceptions.', 'Highway Code rule 99'),
      q('What can under-inflated tyres increase?', 'Fuel use and tyre wear', 'Incorrect pressure also harms grip and vehicle stability.', 'Highway Code annex 6'),
    ]),
    topic('Safety margins', [
      q('What minimum time gap should you keep on a dry, fast road?', 'At least 2 seconds', 'Use a fixed point to measure the gap to the vehicle ahead.', 'Highway Code rule 126'),
      q('What minimum gap should you allow on a wet road?', 'At least 4 seconds', 'The normal two-second gap should be at least doubled.', 'Highway Code rule 126'),
      q('How can ice affect stopping distance?', 'It can make it up to ten times longer', 'Accelerate, steer and brake gently in icy conditions.', 'Highway Code rule 230'),
      q('What is the typical overall stopping distance at 30 mph?', '23 metres', 'This combines about 9 metres thinking distance and 14 metres braking distance.', 'Highway Code rule 126'),
      q('What is the typical overall stopping distance at 70 mph?', '96 metres', 'Real stopping distance can be longer with poor conditions, tyres or concentration.', 'Highway Code rule 126'),
      q('How far should you be able to stop within?', 'The distance you can see to be clear', 'Adjust speed for bends, brows, weather and visibility.', 'Highway Code rule 126'),
      q('If traffic stops inside a tunnel, what gap should you leave?', 'At least 5 metres', 'The gap gives room for evacuation and emergency access.', 'Highway Code rule 126'),
      q('What should you do when another vehicle overtakes you?', 'Maintain a steady course and speed', 'Slow down if necessary to let the vehicle pass safely; never accelerate.', 'Highway Code rule 168'),
    ]),
    topic('Hazard awareness', [
      q('What is a developing hazard?', 'Something that could make you change speed or direction', 'Early recognition creates more time to respond safely.', 'GOV.UK hazard perception guidance'),
      q('Why should you slow near parked vehicles?', 'Doors may open or people may step out', 'Look for occupants, wheels turning and gaps between vehicles.', 'Highway Code rules 152 and 213'),
      q('What should you do before reaching the brow of a hill?', 'Reduce speed and keep well to the left', 'You must be able to stop for hazards hidden beyond the crest.', 'Highway Code rules 166 and 167'),
      q('What should you expect near a school entrance?', 'Children may cross unpredictably', 'Drive slowly and be ready to stop even when no crossing patrol is present.', 'Highway Code rules 205 to 208'),
      q('How should you approach road works?', 'Slow down and obey temporary signs', 'Look for workers, narrow lanes, changed priorities and temporary signals.', 'Highway Code rules 288 to 290'),
      q('Why should you scan well ahead rather than only the vehicle in front?', 'To spot hazards earlier', 'A wider view gives more time for smooth decisions and braking.', 'Highway Code rules 126 and 146'),
      q('What does a parked car with illuminated reversing lights suggest?', 'It may move into your path', 'Slow down and be prepared for the vehicle or a pedestrian to emerge.', 'Highway Code rule 202'),
      q('What should you do when approaching an animal in the road?', 'Slow down and be ready to stop', 'Avoid revving the engine or sounding the horn aggressively.', 'Highway Code rules 214 and 215'),
    ]),
    topic('Vulnerable road users', [
      q('At a junction, who should you give way to when turning?', 'Pedestrians crossing or waiting to cross', 'This applies to a road you are turning into or out of.', 'Highway Code rule H2'),
      q('How much room should you normally give a cyclist when overtaking at up to 30 mph?', 'At least 1.5 metres', 'Give more room at higher speeds and wait if the space is not available.', 'Highway Code rule 163'),
      q('How should you pass a horse rider or horse-drawn vehicle?', 'Under 10 mph with at least 2 metres of space', 'Be patient and avoid sudden noise or movement.', 'Highway Code rule 163'),
      q('What should you do before opening a vehicle door?', 'Check for cyclists and other traffic', 'Using the hand furthest from the door can encourage a shoulder check.', 'Highway Code rule 239'),
      q('Why are motorcyclists easy to miss at junctions?', 'They are smaller and may be obscured', 'Look carefully more than once before emerging or turning.', 'Highway Code rules 211 and 212'),
      q('What should you do when a cyclist continues straight at a junction?', 'Do not cut across them', 'Wait rather than making the cyclist stop or swerve.', 'Highway Code rule H3'),
      q('Which pedestrians may need extra time to cross?', 'Children, older adults and disabled people', 'Their needs may not be immediately obvious, so be patient.', 'Highway Code rules 204 to 210'),
      q('What should you expect from a cyclist on a narrow road?', 'They may ride in the centre of the lane', 'This can be the safest position where overtaking would be dangerous.', 'Highway Code rule 213'),
    ]),
    topic('Other types of vehicle', [
      q('Why do long vehicles sometimes move to the right before turning left?', 'They need extra room to turn', 'Do not try to pass on the inside because the gap can close.', 'Highway Code rule 221'),
      q('What should you do when a bus signals to leave a stop?', 'Give priority when safe', 'Especially in built-up areas, allow it to rejoin without creating danger.', 'Highway Code rule 223'),
      q('Where are the largest blind spots around a large vehicle?', 'Close behind and alongside it', 'If you cannot see its mirrors, its driver may not be able to see you.', 'Highway Code rule 222'),
      q('What is unusual about a tram’s ability to avoid hazards?', 'It cannot steer around them', 'Never obstruct rails and take extra care near tram stops and crossings.', 'Highway Code rules 300 to 307'),
      q('Why should you leave extra space behind a motorcycle?', 'It may stop quickly or be affected by conditions', 'Motorcycles can lose stability on poor surfaces and in strong winds.', 'Highway Code rules 126 and 214'),
      q('What should you expect when overtaking a high-sided vehicle in wind?', 'A sudden change in wind effect', 'Your vehicle may be pulled towards it and pushed away after passing.', 'Highway Code rule 232'),
      q('How should you react to a slow mobility scooter on the road?', 'Be patient and pass only when safe', 'Users may be vulnerable and difficult to see.', 'Highway Code rules 36 to 46 and 214'),
      q('Why might a large vehicle take an unusual line at a roundabout?', 'Its length requires more than one lane', 'Give it room and avoid driving alongside.', 'Highway Code rules 187 and 221'),
    ]),
    topic('Vehicle handling', [
      q('When should you reduce speed for a bend?', 'Before entering the bend', 'Braking while cornering can reduce stability and grip.', 'Highway Code rule 160'),
      q('How should you use the brakes on a long, steep descent?', 'Select a lower gear and brake carefully', 'Engine braking helps prevent the brakes from overheating.', 'Highway Code rule 160'),
      q('What is aquaplaning?', 'Tyres losing contact with the road on surface water', 'Ease off the accelerator and avoid sudden steering or braking.', 'Highway Code rule 227'),
      q('What should you do if the rear of the car skids?', 'Steer carefully into the skid', 'Remove the cause by easing off acceleration or braking and avoid over-correction.', 'Highway Code rule 119'),
      q('How should you brake in an emergency with ABS?', 'Press the brake firmly and keep pressing', 'ABS pulses automatically; steer if necessary while maintaining pressure.', 'Highway Code rule 120'),
      q('Why should cruise control be avoided on slippery roads?', 'It can reduce your control when grip changes', 'Keep direct control of speed in wet, icy or otherwise hazardous conditions.', 'Highway Code rules 125 and 226 to 231'),
      q('How should controls be used on ice or snow?', 'Slowly and smoothly', 'Harsh acceleration, braking or steering can cause loss of grip.', 'Highway Code rule 230'),
      q('What should you do when driving through deep water?', 'Drive slowly in a low gear', 'Test the brakes gently afterwards when safe.', 'Highway Code rule 227'),
    ]),
    topic('Motorway rules', [
      q('Who has priority when you join a motorway?', 'Traffic already on the motorway', 'Match traffic speed on the slip road and merge into a safe gap.', 'Highway Code rule 259'),
      q('Which lane should you normally use on a motorway?', 'The left lane', 'Use other lanes for overtaking and return left when it is safe.', 'Highway Code rules 264 and 265'),
      q('What does a red X above a motorway lane mean?', 'The lane is closed', 'You must not drive in that lane beyond the signal.', 'Highway Code rules 258 and 269'),
      q('When may you use the hard shoulder?', 'Only in an emergency or when directed', 'On some motorways signs may open it as a running lane.', 'Highway Code rules 269 and 270'),
      q('Should you place a warning triangle on a motorway?', 'No', 'It is too dangerous to walk into motorway traffic to place one.', 'Highway Code rule 274'),
      q('What should you do if your vehicle breaks down and can reach a safe place?', 'Leave the carriageway to the left', 'Use an emergency area, service area, exit or hard shoulder if available.', 'Highway Code rules 275 to 278'),
      q('What colour studs separate motorway lanes?', 'White', 'Red marks the left edge, amber the central reservation and green a slip road.', 'Highway Code rule 132'),
      q('What should you do if you miss your motorway exit?', 'Continue to the next exit', 'Never reverse, stop or cross the central reservation.', 'Highway Code rules 263 and 270'),
    ]),
    topic('Rules of the road', [
      q('Who normally has priority at a roundabout?', 'Traffic approaching from the right', 'Give way unless signs, signals or markings indicate otherwise.', 'Highway Code rule 185'),
      q('When may you enter a yellow box junction?', 'When your exit is clear', 'The exception is waiting to turn right when blocked by oncoming traffic or other right-turners.', 'Highway Code rule 174'),
      q('How close to a junction should you avoid parking?', 'Within 10 metres', 'Do not park opposite or near a junction except in an authorised space.', 'Highway Code rule 243'),
      q('When may you pass traffic on the left?', 'In slow queues when your lane moves faster', 'Do not weave between lanes to overtake.', 'Highway Code rule 163 and 268'),
      q('What does a solid white line nearest you generally mean?', 'Do not cross or straddle it', 'Limited exceptions apply, including entering premises or passing certain slow road users when safe.', 'Highway Code rule 129'),
      q('May you park on zigzag lines at a pedestrian crossing?', 'No', 'The markings protect visibility and access to the crossing.', 'Highway Code rules 191 and 240'),
      q('What should you do at a STOP sign?', 'Stop behind the line', 'You must stop even if the road appears clear, then proceed when safe.', 'Highway Code rule 171'),
      q('When should you signal at a roundabout when taking the first exit?', 'Signal left on approach', 'Keep to the left unless signs or markings direct otherwise.', 'Highway Code rule 186'),
    ]),
    topic('Road and traffic signs', [
      q('What shape is normally used for warning signs?', 'A red-bordered triangle', 'Warnings tell you about hazards ahead.', 'Highway Code traffic signs'),
      q('What do circular signs usually give?', 'Orders', 'Red circles prohibit and blue circles usually give positive instructions.', 'Highway Code traffic signs'),
      q('What is distinctive about the STOP sign?', 'It is octagonal', 'Its unique shape makes it recognisable even when partly obscured.', 'Highway Code traffic signs'),
      q('What is distinctive about the Give Way sign?', 'It is an upside-down triangle', 'Its unique outline helps recognition from the back or when obscured.', 'Highway Code traffic signs'),
      q('What does the national speed-limit sign mean for a car on a single carriageway?', '60 mph maximum', 'The limit is 70 mph on dual carriageways and motorways unless signs say otherwise.', 'Highway Code rule 124'),
      q('What must you do at a steady amber traffic light?', 'Stop unless already too close to stop safely', 'Amber follows green and precedes red.', 'Highway Code light signals'),
      q('What does a blue circular sign with a white arrow mean?', 'You must travel in the shown direction', 'Blue circles generally state a positive requirement.', 'Highway Code traffic signs'),
      q('What does a red ring around a speed number mean?', 'The maximum speed allowed', 'The signed limit is a legal maximum, not a target.', 'Highway Code rule 124 and traffic signs'),
      q('What does this sign mean?', 'Give way', 'Slow down on approach and give way to traffic on the road you are joining.', 'Highway Code traffic signs', { image: './assets/signs/give-way.jpg', imageAlt: 'An inverted white triangle with a thick red border' }),
      q('What hazard does this sign warn about?', 'Pedestrians in the road ahead', 'Be prepared to slow down and give people plenty of room.', 'Highway Code traffic signs', { image: './assets/signs/pedestrians.jpg', imageAlt: 'A red warning triangle containing a walking person' }),
      q('What hazard does this sign warn about?', 'Accompanied horses or ponies', 'Slow down, pass wide and quietly, and be ready to stop.', 'Highway Code rules 214 and traffic signs', { image: './assets/signs/horses.jpg', imageAlt: 'A red warning triangle containing a horse' }),
      q('What does this warning sign mean?', 'Uneven road', 'Reduce speed because the uneven surface could affect steering or stability.', 'Highway Code traffic signs', { image: './assets/signs/uneven-road.jpg', imageAlt: 'A red warning triangle containing two humps' }),
      q('What does this sign mean?', 'Other danger', 'A plate normally explains the specific hazard; approach cautiously.', 'Highway Code traffic signs', { image: './assets/signs/other-danger.jpg', imageAlt: 'A red warning triangle containing an exclamation mark' }),
      q('What does this sign mean?', 'No entry for vehicular traffic', 'Do not drive past this sign.', 'Highway Code traffic signs', { image: './assets/signs/no-entry.jpg', imageAlt: 'A solid red circle with a horizontal white bar' }),
      q('What speed limit is shown?', '30 mph', 'The red circle makes the number a mandatory maximum speed.', 'Highway Code rule 124 and traffic signs', { image: './assets/signs/30-limit.jpg', imageAlt: 'The number 30 inside a red circle' }),
      q('What does this sign mean for a car?', 'National speed limit applies', 'For a car this is normally 60 mph on a single carriageway and 70 mph on a dual carriageway.', 'Highway Code rule 124 and traffic signs', { image: './assets/signs/national-speed-limit.jpg', imageAlt: 'A white circle crossed by a single black diagonal stripe' }),
    ]),
    topic('Documents', [
      q('What is the minimum motor insurance needed to drive on public roads?', 'Third-party insurance', 'It covers injury or damage caused to other people and their property.', 'Highway Code annex 3'),
      q('When does a typical car first need an MOT in Great Britain?', 'By the third anniversary of registration', 'After that it normally needs an MOT each year; limited exceptions apply.', 'GOV.UK getting an MOT'),
      q('What does SORN mean?', 'Statutory Off Road Notification', 'A SORN tells DVLA that a vehicle is not being used or kept on a public road.', 'GOV.UK make a SORN'),
      q('What details must you provide after a collision causing damage or injury?', 'Your name, address and vehicle details', 'You must also provide the owner’s details and insurance information when required.', 'Highway Code rule 286'),
      q('How soon must a reportable collision be reported if details were not exchanged?', 'As soon as possible and within 24 hours', 'Report it to the police when required by law.', 'Highway Code rule 286'),
      q('What happens if a new driver receives 6 penalty points within 2 years?', 'The driving licence is revoked', 'The driver normally has to apply again and retake both tests.', 'Highway Code annex 5'),
      q('Who must be told when your name or permanent address changes?', 'DVLA', 'Your driving licence and vehicle registration details must be kept current.', 'Highway Code annex 3'),
      q('Does an MOT prove a vehicle is safe for the whole year?', 'No', 'The driver remains responsible for keeping the vehicle roadworthy at all times.', 'Highway Code rule 89 and annex 3'),
    ]),
    topic('Incidents, accidents and emergencies', [
      q('What should be your first priority at a collision scene?', 'Prevent further danger', 'Protect yourself and others before trying to help casualties.', 'Highway Code annex 7'),
      q('How far behind a broken-down vehicle should a warning triangle be placed on an ordinary road?', 'At least 45 metres', 'Only place it when safe, and never place one on a motorway.', 'Highway Code rule 274'),
      q('What information should you give when calling emergency services?', 'Location, injuries and hazards', 'Give clear details and follow the call handler’s instructions.', 'Highway Code annex 7'),
      q('Should an injured motorcyclist’s helmet normally be removed?', 'No, unless it is essential', 'Removing it unnecessarily could worsen neck or spinal injury.', 'Highway Code annex 7'),
      q('What should you do if a vehicle catches fire?', 'Get everyone out and call the emergency services', 'Do not open the bonnet because extra air can intensify the fire.', 'Highway Code rule 283'),
      q('How should a burn be cooled?', 'With cool running water for at least 20 minutes', 'Do not apply creams and do not remove material stuck to the burn.', 'Highway Code annex 7'),
      q('What should you do if a casualty is not breathing normally?', 'Call 999 and start CPR', 'Follow emergency call-handler instructions and use an AED if available.', 'Highway Code annex 7'),
      q('What should you do with an unconscious casualty who is breathing?', 'Place them in the recovery position', 'Keep the airway open and monitor breathing unless injury makes movement unsafe.', 'Highway Code annex 7'),
    ]),
    topic('Vehicle loading', [
      q('What must you do with luggage carried in a vehicle?', 'Secure it so it cannot move', 'Loose items can affect control or injure occupants in sudden braking.', 'Highway Code rules 98 and 229'),
      q('What should you check after loading a vehicle heavily?', 'Tyre pressures and headlight aim', 'Use manufacturer guidance because load affects handling, tyres and dazzle.', 'Highway Code rule 98 and annex 6'),
      q('What is the maximum speed for a car towing a trailer on a single carriageway?', '50 mph', 'Lower signed limits still apply.', 'Highway Code rule 124'),
      q('What is the maximum speed for a car towing on a motorway or dual carriageway?', '60 mph', 'A towing combination must not exceed this even where cars may travel at 70 mph.', 'Highway Code rule 124'),
      q('May a towing vehicle use the right-hand lane of a three-lane motorway?', 'No', 'Use of the outside lane is prohibited when towing, subject to exceptional directions.', 'Highway Code rule 265'),
      q('Why must a trailer load be distributed carefully?', 'To keep the outfit stable', 'Follow the permitted nose weight and keep heavy items low and near the axle.', 'Highway Code rules 98 and 228'),
      q('What is the purpose of a trailer breakaway cable?', 'To apply the trailer brakes if it detaches', 'It must be correctly attached to a suitable point on the towing vehicle.', 'Highway Code rule 98 and towing guidance'),
      q('What must you check before towing a trailer?', 'The coupling, lights, tyres and load', 'A full safety check helps prevent detachment, instability and lighting offences.', 'Highway Code rules 98 and 228'),
    ]),
  ],
}
