import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowLeft, Check, Eye, MousePointerClick, Play, RotateCcw, Trophy } from 'lucide-react'
import { generateHazardTest, HAZARD_MAX_SCORE, HAZARD_PASS_MARK, scoreClip } from './hazardClips.js'

function Results({ clips, responses, onRestart, onExit }) {
  const results = clips.map((clip) => ({ clip, clicks: responses[clip.id] || [], ...scoreClip(clip, responses[clip.id] || []) }))
  const total = results.reduce((sum, item) => sum + item.score, 0)
  return <main className="hazard-results"><section className={`exam-result-hero ${total >= HAZARD_PASS_MARK ? 'passed' : 'not-passed'}`}><div className="celebration">{total >= HAZARD_PASS_MARK ? <Trophy size={38} /> : <RotateCcw size={34} />}</div><span className="eyebrow">HAZARD PERCEPTION COMPLETE</span><h1>{total >= HAZARD_PASS_MARK ? 'You passed.' : 'Keep scanning earlier.'}</h1><p>{total >= HAZARD_PASS_MARK ? 'You reached the pass mark.' : `You need ${HAZARD_PASS_MARK} points to pass.`}</p><div className="result-grid"><div><strong>{total}/75</strong><span>score</span></div><div><strong>44/75</strong><span>pass mark</span></div><div><strong>{results.reduce((sum, item) => sum + item.clicks.length, 0)}</strong><span>clicks</span></div></div><div className="finished-actions"><button className="button button-secondary" onClick={onExit}>Back home</button><button className="button button-primary" onClick={onRestart}><RotateCcw size={17} /> New clip set</button></div></section><section className="hazard-review"><span className="eyebrow">CLIP REVIEW</span><h2>Developing hazards and timing</h2><p className="review-intro">Training annotations for open-licence footage, not official DVSA scoring windows.</p>{results.map(({ clip, clicks, score, invalidPattern, hazardScores }, index) => <article key={clip.id}><div className="hazard-review-score"><span>Clip {index + 1}</span><strong>{score}/{clip.hazards.length * 5}</strong></div><div><h3>{clip.title.replace('.webm', '')}</h3><p>{clicks.length} click{clicks.length === 1 ? '' : 's'}. {invalidPattern && 'Pattern clicking made this clip score zero.'}</p>{clip.hazards.map((hazard, hazardIndex) => <div className="hazard-explanation" key={hazard.label}><Check size={16} /><span><strong>Hazard {hazardIndex + 1}: {hazardScores[hazardIndex]}/5</strong>{hazard.label}</span></div>)}<small><a href={clip.sourceUrl} target="_blank" rel="noreferrer">{clip.author} · {clip.license} · Wikimedia Commons</a></small></div></article>)}</section></main>
}

export default function HazardSession({ onExit, onComplete }) {
  const [attempt, setAttempt] = useState(0), clips = useMemo(() => generateHazardTest(`${Date.now()}-${attempt}-${Math.random()}`), [attempt])
  const [phase, setPhase] = useState('intro'), [index, setIndex] = useState(0), [responses, setResponses] = useState({}), [flash, setFlash] = useState(false), [mediaError, setMediaError] = useState(false)
  const videoRef = useRef(null), responsesRef = useRef({}), reported = useRef(false), clip = clips[index], clickCount = responses[clip?.id]?.length || 0
  async function startClip() { try { setMediaError(false); videoRef.current.currentTime = 0; await videoRef.current.play(); setPhase('playing') } catch { setMediaError(true) } }
  function recordClick() { if (phase !== 'playing' || !videoRef.current) return; const time = videoRef.current.currentTime; const next = { ...responsesRef.current, [clip.id]: [...(responsesRef.current[clip.id] || []), time] }; responsesRef.current = next; setResponses(next); setFlash(true); window.setTimeout(() => setFlash(false), 180) }
  function finishClip() { if (phase !== 'playing') return; videoRef.current?.pause(); if (index === clips.length - 1) { const total = clips.reduce((sum, item) => sum + scoreClip(item, responsesRef.current[item.id] || []).score, 0); if (!reported.current) { reported.current = true; onComplete({ score: total, total: HAZARD_MAX_SCORE, elapsed: clips.reduce((sum, item) => sum + item.duration, 0) }) } setPhase('finished') } else setPhase('between') }
  function restart() { reported.current = false; responsesRef.current = {}; setAttempt((value) => value + 1); setIndex(0); setResponses({}); setPhase('intro'); setMediaError(false) }
  if (phase === 'finished') return <div className="session-shell"><Results clips={clips} responses={responses} onRestart={restart} onExit={onExit} /></div>
  if (phase === 'intro') return <div className="session-shell"><header className="session-header hazard-header"><button className="button button-ghost" onClick={onExit}><ArrowLeft size={18} /> Exit</button><strong>Hazard perception</strong><span>14 clips · 15 hazards</span></header><main className="hazard-intro"><div className="hazard-intro-icon"><Eye size={40} /></div><span className="eyebrow">PART TWO</span><h1>Spot hazards as they develop.</h1><p>You will see 14 silent road clips. Thirteen contain one developing hazard and one contains two. Click as soon as something would make you change speed or direction.</p><div className="hazard-rule-grid"><div><MousePointerClick size={22} /><strong>Click early</strong><span>Each hazard scores from 5 down to 1.</span></div><div><AlertTriangle size={22} /><strong>Avoid patterns</strong><span>Repeated or rhythmic clicking scores zero.</span></div><div><Play size={22} /><strong>One viewing</strong><span>You cannot pause, rewind, or change a response.</span></div></div><button className="button button-primary" onClick={() => setPhase('ready')}><Play size={17} /> Begin hazard test</button><small>Practice footage is openly licensed and is not from the DVSA test.</small></main></div>
  return <div className="session-shell"><header className="session-header hazard-header"><button className="button button-ghost" onClick={onExit}><ArrowLeft size={18} /> Exit</button><strong>Hazard perception</strong><span>Clip {index + 1} of 14</span></header><main className="hazard-stage">{phase === 'between' ? <section className="between-clips"><Check size={30} /><span className="eyebrow">RESPONSE SAVED</span><h1>Clip {index + 1} complete</h1><p>{clickCount} click{clickCount === 1 ? '' : 's'} recorded. Your score stays hidden.</p><button className="button button-primary" onClick={() => { setIndex(index + 1); setPhase('ready'); setMediaError(false) }}>Continue to clip {index + 2}</button></section> : <section className="hazard-player-card"><div className={`hazard-video-wrap ${flash ? 'clicked' : ''}`} onClick={recordClick} onKeyDown={(event) => (event.key === 'Enter' || event.key === ' ') && recordClick()} role="button" tabIndex={phase === 'playing' ? 0 : -1} aria-label="Road clip. Activate when you spot a developing hazard."><video key={clip.id} ref={videoRef} src={clip.src} muted playsInline preload="metadata" onTimeUpdate={(event) => event.currentTarget.currentTime >= clip.duration && finishClip()} onEnded={finishClip} onError={() => setMediaError(true)} /><div className="hazard-click-flash"><MousePointerClick size={30} /></div>{phase === 'ready' && <div className="video-cover"><span>Clip {index + 1}</span><button className="button button-primary" onClick={(event) => { event.stopPropagation(); startClip() }}><Play size={17} /> Start clip</button></div>}</div>{mediaError && <div className="media-error"><AlertTriangle size={17} /> The clip could not load.<button className="button button-secondary" onClick={startClip}>Retry</button></div>}<div className="hazard-controls"><div><span className="live-dot" /> Clip in progress</div><button className="button button-primary spot-button" onClick={recordClick} disabled={phase !== 'playing'}><MousePointerClick size={18} /> Spot hazard</button><span>{clickCount} click{clickCount === 1 ? '' : 's'}</span></div><p className="hazard-help">Click the video or use the button when a hazard begins to develop.</p></section>}</main></div>
}
